### ISSUE TITLE
Benchmark - compared to std library

### ISSUE THREAD

**Issue by prassee** [bradenaw/juniper#2]
It would be good to see benchmarks with std lib such suite would help improve the library. I can help with that if the author of this project is willing to drive the project on this direction.

**Comment by bradenaw** [comment]
Which comparisons are you hoping to see? There's one already in there for `container/tree` vs. the map builtin: https://github.com/bradenaw/juniper/blob/main/container/tree/btree_benchmark_test.go

Are there others that'd be helpful?
