### ISSUE TITLE
impossible to use tree.Range

### ISSUE THREAD

**Issue by Claus1** [bradenaw/juniper#6]
tree.Range requests Bound as parameters, but for making Bound there is no access to type boundType and its values. The most usefull b-tree search functions are inaccessible due names without reason.

**Comment by bradenaw** [comment]
These constructors produce `Bound`s:
- `Included(k)` https://pkg.go.dev/github.com/bradenaw/juniper/container/tree#Included
- `Excluded(k)` https://pkg.go.dev/github.com/bradenaw/juniper/container/tree#Excluded
- `Unbounded()` https://pkg.go.dev/github.com/bradenaw/juniper/container/tree#Unbounded
