### ISSUE TITLE
This package now requires go1.21

### ISSUE THREAD

**Issue by ncw** [bradenaw/juniper#8]
In 0ecc9cb6e19fd3d711587f070d217d7e7d4df561

The value of `go` in `go.mod` was increased from `go 1.18` to `go 1.21`.

This forces all users of this package to upgrade their go to 1.21

```
$ go get github.com/bradenaw/juniper
go: upgraded go 1.19 => 1.21
go: added toolchain go1.21.3
go: upgraded github.com/bradenaw/juniper v0.13.1 => v0.14.3
```

I'm not sure if that was your intention or not. Being able to support old versions is very useful for a library and if this library works with `go 1.18` then I suggest you revert the `go.mod` change and set it back to `go 1.18`. If it doesn't work with `go 1.18` then pick the oldest version of go it does work with.

Happy to send a PR for this if you think it is a good idea.

**Comment by bradenaw** [comment]
It does currently require 1.21 to build, yes, since I swapped out some of the implementations in `xslices` and a few other places to just call the standard library ones introduced in 1.21.

I could perhaps be talked into supporting back to 1.20, since [that's as far back as Go itself supports](https://go.dev/doc/devel/release#policy).

Are you currently or interested in using the package in a context where it's difficult to upgrade?

**Comment by ncw** [comment]
This is a dependency of a dependency of rclone. I accidentally upgraded it and noticed that rclone switched to go1.21. I like to give my users 3 go versions as there are lots of distros with older versions.

I undid the accidental upgrade and all is fine with rclone now, but I thought I'd make this issue to bring it to your attention.

I didn't realise before that, that the go.mod version is infectious. All it takes is one dependency to declare a new go version and boom your go.mod changes.

So that might be something to bear in mind!

Anyway supporting two Go versions is what Go does so that should be the minimum I think, but most libraries go further in my experience.

**Comment by bradenaw** [comment]
Good point! I'll take a look this week.

**Comment by bradenaw** [comment]
https://github.com/bradenaw/juniper/releases/tag/v0.15.0 - let me know if that works for you.
